apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'web.hook'
      
    receivers:
    - name: 'web.hook'
      webhook_configs:
      - url: 'http://example.com/webhook'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kodekloud-record-store-alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kodekloud-record-store-alertmanager
  template:
    metadata:
      labels:
        app: kodekloud-record-store-alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:latest
          ports:
            - containerPort: 9093
          volumeMounts:
            - name: config-volume
              mountPath: /etc/alertmanager
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager-config
---
apiVersion: v1
kind: Service
metadata:
  name: kodekloud-record-store-alertmanager
spec:
  selector:
    app: kodekloud-record-store-alertmanager
  ports:
    - port: 9093
      targetPort: 9093
  type: ClusterIP