apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - /etc/prometheus/alert_rules.yml
    
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      - job_name: 'api'
        static_configs:
          - targets: ['kodekloud-record-store:8000']
      
      - job_name: 'pushgateway'
        static_configs:
          - targets: ['kodekloud-record-store-pushgateway:9091']
  
  alert_rules.yml: |
    groups:
      - name: example
        rules:
          - alert: HighRequestLatency
            expr: job:request_latency_seconds:mean5m{job="api"} > 0.5
            for: 10m
            labels:
              severity: page
            annotations:
              summary: High request latency