apiVersion: v1
kind: Service
metadata:
  name: kodekloud-record-store
spec:
  selector:
    app: kodekloud-record-store
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: "{{ .Values.service.type }}"
